GET http://localhost:4004/sap/opu/odata/FoodService/FoodEntity?filter=group=dumb HTTP/1.1
###
POST http://localhost:4004/sap/opu/odata/FoodService/FoodEntity HTTP/1.1
Content-Type: application/json
{"food_name":"Prasanna Yuk","scientific_name":"distasteful food","group":"dumb","sub_group":"dumbass"}